config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts

  root to: 'home#landing'

  get 'pdf_file', to: 'home#pdf'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :authenticatable, polymorphic: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  helper_method :current_user

  protect_from_forgery with: :exception
  rescue_from ActionController::InvalidAuthenticityToken do
    flash[:alert] = I18n.t('app.authenticity_token_expired')
    redirect_back fallback_location: root_path, allow_other_host: false
  end

  before_action :authenticate_account!

  private

  # A shorthand for passing locals to views, avoiding implicitly passed instance
  # variables.
  #
  # The following calls are equivalent to each other:
  #   render action: :new, locals: { the_anser: 42 }
  #   expose :new, the_answer: 42
  #
  #   render locals: { the_anser: 42 }
  #   expose the_anser: 42
  #
  # @param action [Symbol] action to render, only necessary if not default
  # @param locals [Hash<Symbol, Object>] locals to be passed to the view
  # @return [void]
  def expose(action = nil, **locals)
    render action: action, locals: locals
  end

  def current_user
    @current_user ||= current_account&.authenticatable
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ActionController::Base
  def landing
    rta = RubyTikaApp.new(Rails.root.join("public", "advanced.pdf").to_s)
    @text = rta.to_text
    PdfParserWorker.perform_async
  end

  def pdf
    path = Rails.root.join("public", "advanced.pdf").to_s
    send_file(path)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Translate Rails standard flash keys for Bootstrap
  def flash_alert_class(name)
    case name
    when 'notice' then 'alert-success'
    when 'alert'  then 'alert-danger'
    else name
    end
  end
end

app/views/home/landing.html.erb
<h1>PDF Contents</h1>

<%= link_to 'File', pdf_file_path %>

<p>
  <%= @text %>
</p>

app/views/layouts/_favicon.html.erb
<link rel="shortcut icon" href="/favicon.ico">

<% %w(36 48 72 96 144 192).each do |size| %>
    <link href="<%= "/android-chrome-#{size}x#{size}.png" %>"
          rel="icon"
          type="image/png"
          sizes="<%= "#{size}x#{size}" %>" />
<% end %>

<% %w(57 60 72 76 114 120 144 152 180).each do |size| %>
    <link href="<%= "/apple-touch-icon-#{size}x#{size}.png" %>"
          rel="apple-touch-icon"
          type="image/png"
          sizes="<%= "#{size}x#{size}" %>" />
<% end %>
<link content="apple-touch-icon-precomposed.png"
      rel="apple-touch-icon-precomposed" />

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div class="row-fluid alerts">
    <% flash.each do |name, message| %>
      <div class="alert alert-dismissible <%= flash_alert_class(name) %> fade show" role="alert">
        <div class="container">
          <button class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_ID'].present? %>
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script>
  SETTINGS.google_analytics_id = "<%= ENV['GOOGLE_ANALYTICS_ID'] %>"
</script>
<script async src="<%= "https://www.googletagmanager.com/gtag/js?id=#{ENV['GOOGLE_ANALYTICS_ID']}" %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());
</script>
<% end %>

app/views/layouts/_js_setup.html.erb
<script>
  var SETTINGS = {};
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>

    <title><%= yield(:page_title).presence || t('app.default_title') %></title>

    <%= render partial: 'layouts/js_setup' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'layouts/google_analytics' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
    <%= render partial: 'layouts/favicon' %>
    <link rel='manifest' href='/manifest.json'>
  </head>

  <body>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>
  </body>
</html>